// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipeline.proto

package com.googlecode.protobuf.pro.stream.example.pipeline;

public final class Pipeline {
  private Pipeline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PeerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string hostname = 1;
    boolean hasHostname();
    String getHostname();
    
    // required int32 port = 2;
    boolean hasPort();
    int getPort();
  }
  public static final class Peer extends
      com.google.protobuf.GeneratedMessage
      implements PeerOrBuilder {
    // Use Peer.newBuilder() to construct.
    private Peer(Builder builder) {
      super(builder);
    }
    private Peer(boolean noInit) {}
    
    private static final Peer defaultInstance;
    public static Peer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Peer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Peer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Peer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string hostname = 1;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object hostname_;
    public boolean hasHostname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          hostname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPort() {
      return port_;
    }
    
    private void initFields() {
      hostname_ = "";
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHostname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Peer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Peer_fieldAccessorTable;
      }
      
      // Construct using com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hostname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.getDefaultInstance();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer build() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer buildPartial() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer result = new com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostname_ = hostname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer other) {
        if (other == com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.getDefaultInstance()) return this;
        if (other.hasHostname()) {
          setHostname(other.getHostname());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHostname()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hostname_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string hostname = 1;
      private java.lang.Object hostname_ = "";
      public boolean hasHostname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          hostname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHostname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }
      public Builder clearHostname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      void setHostname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
      }
      
      // required int32 port = 2;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Peer)
    }
    
    static {
      defaultInstance = new Peer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Peer)
  }
  
  public interface PostOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string filename = 1;
    boolean hasFilename();
    String getFilename();
    
    // repeated .Peer peer = 2;
    java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> 
        getPeerList();
    com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer getPeer(int index);
    int getPeerCount();
    java.util.List<? extends com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder> 
        getPeerOrBuilderList();
    com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder getPeerOrBuilder(
        int index);
  }
  public static final class Post extends
      com.google.protobuf.GeneratedMessage
      implements PostOrBuilder {
    // Use Post.newBuilder() to construct.
    private Post(Builder builder) {
      super(builder);
    }
    private Post(boolean noInit) {}
    
    private static final Post defaultInstance;
    public static Post getDefaultInstance() {
      return defaultInstance;
    }
    
    public Post getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Post_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Post_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string filename = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object filename_;
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          filename_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .Peer peer = 2;
    public static final int PEER_FIELD_NUMBER = 2;
    private java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> peer_;
    public java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> getPeerList() {
      return peer_;
    }
    public java.util.List<? extends com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder> 
        getPeerOrBuilderList() {
      return peer_;
    }
    public int getPeerCount() {
      return peer_.size();
    }
    public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer getPeer(int index) {
      return peer_.get(index);
    }
    public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder getPeerOrBuilder(
        int index) {
      return peer_.get(index);
    }
    
    private void initFields() {
      filename_ = "";
      peer_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPeerCount(); i++) {
        if (!getPeer(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilenameBytes());
      }
      for (int i = 0; i < peer_.size(); i++) {
        output.writeMessage(2, peer_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilenameBytes());
      }
      for (int i = 0; i < peer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, peer_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Post_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Post_fieldAccessorTable;
      }
      
      // Construct using com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPeerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (peerBuilder_ == null) {
          peer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          peerBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.getDefaultInstance();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post build() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post buildPartial() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post result = new com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        if (peerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            peer_ = java.util.Collections.unmodifiableList(peer_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.peer_ = peer_;
        } else {
          result.peer_ = peerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post other) {
        if (other == com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          setFilename(other.getFilename());
        }
        if (peerBuilder_ == null) {
          if (!other.peer_.isEmpty()) {
            if (peer_.isEmpty()) {
              peer_ = other.peer_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePeerIsMutable();
              peer_.addAll(other.peer_);
            }
            onChanged();
          }
        } else {
          if (!other.peer_.isEmpty()) {
            if (peerBuilder_.isEmpty()) {
              peerBuilder_.dispose();
              peerBuilder_ = null;
              peer_ = other.peer_;
              bitField0_ = (bitField0_ & ~0x00000002);
              peerBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPeerFieldBuilder() : null;
            } else {
              peerBuilder_.addAllMessages(other.peer_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFilename()) {
          
          return false;
        }
        for (int i = 0; i < getPeerCount(); i++) {
          if (!getPeer(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filename_ = input.readBytes();
              break;
            }
            case 18: {
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder subBuilder = com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPeer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string filename = 1;
      private java.lang.Object filename_ = "";
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFilename(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      void setFilename(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
      }
      
      // repeated .Peer peer = 2;
      private java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> peer_ =
        java.util.Collections.emptyList();
      private void ensurePeerIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          peer_ = new java.util.ArrayList<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer>(peer_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder> peerBuilder_;
      
      public java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> getPeerList() {
        if (peerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(peer_);
        } else {
          return peerBuilder_.getMessageList();
        }
      }
      public int getPeerCount() {
        if (peerBuilder_ == null) {
          return peer_.size();
        } else {
          return peerBuilder_.getCount();
        }
      }
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer getPeer(int index) {
        if (peerBuilder_ == null) {
          return peer_.get(index);
        } else {
          return peerBuilder_.getMessage(index);
        }
      }
      public Builder setPeer(
          int index, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer value) {
        if (peerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeerIsMutable();
          peer_.set(index, value);
          onChanged();
        } else {
          peerBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPeer(
          int index, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder builderForValue) {
        if (peerBuilder_ == null) {
          ensurePeerIsMutable();
          peer_.set(index, builderForValue.build());
          onChanged();
        } else {
          peerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPeer(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer value) {
        if (peerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeerIsMutable();
          peer_.add(value);
          onChanged();
        } else {
          peerBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPeer(
          int index, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer value) {
        if (peerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeerIsMutable();
          peer_.add(index, value);
          onChanged();
        } else {
          peerBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPeer(
          com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder builderForValue) {
        if (peerBuilder_ == null) {
          ensurePeerIsMutable();
          peer_.add(builderForValue.build());
          onChanged();
        } else {
          peerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPeer(
          int index, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder builderForValue) {
        if (peerBuilder_ == null) {
          ensurePeerIsMutable();
          peer_.add(index, builderForValue.build());
          onChanged();
        } else {
          peerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPeer(
          java.lang.Iterable<? extends com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer> values) {
        if (peerBuilder_ == null) {
          ensurePeerIsMutable();
          super.addAll(values, peer_);
          onChanged();
        } else {
          peerBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPeer() {
        if (peerBuilder_ == null) {
          peer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          peerBuilder_.clear();
        }
        return this;
      }
      public Builder removePeer(int index) {
        if (peerBuilder_ == null) {
          ensurePeerIsMutable();
          peer_.remove(index);
          onChanged();
        } else {
          peerBuilder_.remove(index);
        }
        return this;
      }
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder getPeerBuilder(
          int index) {
        return getPeerFieldBuilder().getBuilder(index);
      }
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder getPeerOrBuilder(
          int index) {
        if (peerBuilder_ == null) {
          return peer_.get(index);  } else {
          return peerBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder> 
           getPeerOrBuilderList() {
        if (peerBuilder_ != null) {
          return peerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(peer_);
        }
      }
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder addPeerBuilder() {
        return getPeerFieldBuilder().addBuilder(
            com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.getDefaultInstance());
      }
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder addPeerBuilder(
          int index) {
        return getPeerFieldBuilder().addBuilder(
            index, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.getDefaultInstance());
      }
      public java.util.List<com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder> 
           getPeerBuilderList() {
        return getPeerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder> 
          getPeerFieldBuilder() {
        if (peerBuilder_ == null) {
          peerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder, com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.PeerOrBuilder>(
                  peer_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          peer_ = null;
        }
        return peerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Post)
    }
    
    static {
      defaultInstance = new Post(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Post)
  }
  
  public interface GetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string filename = 1;
    boolean hasFilename();
    String getFilename();
  }
  public static final class Get extends
      com.google.protobuf.GeneratedMessage
      implements GetOrBuilder {
    // Use Get.newBuilder() to construct.
    private Get(Builder builder) {
      super(builder);
    }
    private Get(boolean noInit) {}
    
    private static final Get defaultInstance;
    public static Get getDefaultInstance() {
      return defaultInstance;
    }
    
    public Get getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Get_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Get_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string filename = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object filename_;
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          filename_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      filename_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilenameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilenameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.GetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Get_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.internal_static_Get_fieldAccessorTable;
      }
      
      // Construct using com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.getDefaultInstance();
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get build() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get buildPartial() {
        com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get result = new com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get other) {
        if (other == com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          setFilename(other.getFilename());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFilename()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filename_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string filename = 1;
      private java.lang.Object filename_ = "";
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFilename(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      void setFilename(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Get)
    }
    
    static {
      defaultInstance = new Get(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Get)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Peer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Peer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Post_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Post_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Get_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pipeline.proto\"&\n\004Peer\022\020\n\010hostname\030\001 \002" +
      "(\t\022\014\n\004port\030\002 \002(\005\"-\n\004Post\022\020\n\010filename\030\001 \002" +
      "(\t\022\023\n\004peer\030\002 \003(\0132\005.Peer\"\027\n\003Get\022\020\n\010filena" +
      "me\030\001 \002(\tB?\n3com.googlecode.protobuf.pro." +
      "stream.example.pipelineB\010Pipeline"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Peer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Peer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Peer_descriptor,
              new java.lang.String[] { "Hostname", "Port", },
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.class,
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Peer.Builder.class);
          internal_static_Post_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Post_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Post_descriptor,
              new java.lang.String[] { "Filename", "Peer", },
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.class,
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Post.Builder.class);
          internal_static_Get_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Get_descriptor,
              new java.lang.String[] { "Filename", },
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.class,
              com.googlecode.protobuf.pro.stream.example.pipeline.Pipeline.Get.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
