// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package com.googlecode.protobuf.pro.duplex.test;

public final class PingPong {
  private PingPong() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Ping extends
      com.google.protobuf.GeneratedMessage {
    // Use Ping.newBuilder() to construct.
    private Ping() {
      initFields();
    }
    private Ping(boolean noInit) {}
    
    private static final Ping defaultInstance;
    public static Ping getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ping getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.duplex.test.PingPong.internal_static_Ping_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.duplex.test.PingPong.internal_static_Ping_fieldAccessorTable;
    }
    
    // required int32 processingTime = 1;
    public static final int PROCESSINGTIME_FIELD_NUMBER = 1;
    private boolean hasProcessingTime;
    private int processingTime_ = 0;
    public boolean hasProcessingTime() { return hasProcessingTime; }
    public int getProcessingTime() { return processingTime_; }
    
    // required int32 pongDataLength = 2;
    public static final int PONGDATALENGTH_FIELD_NUMBER = 2;
    private boolean hasPongDataLength;
    private int pongDataLength_ = 0;
    public boolean hasPongDataLength() { return hasPongDataLength; }
    public int getPongDataLength() { return pongDataLength_; }
    
    // required bytes pingData = 3;
    public static final int PINGDATA_FIELD_NUMBER = 3;
    private boolean hasPingData;
    private com.google.protobuf.ByteString pingData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPingData() { return hasPingData; }
    public com.google.protobuf.ByteString getPingData() { return pingData_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasProcessingTime) return false;
      if (!hasPongDataLength) return false;
      if (!hasPingData) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProcessingTime()) {
        output.writeInt32(1, getProcessingTime());
      }
      if (hasPongDataLength()) {
        output.writeInt32(2, getPongDataLength());
      }
      if (hasPingData()) {
        output.writeBytes(3, getPingData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProcessingTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getProcessingTime());
      }
      if (hasPongDataLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPongDataLength());
      }
      if (hasPingData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPingData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.duplex.test.PingPong.Ping prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.duplex.test.PingPong.Ping result;
      
      // Construct using com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.duplex.test.PingPong.Ping();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.duplex.test.PingPong.Ping internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.duplex.test.PingPong.Ping();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Ping getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Ping build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.duplex.test.PingPong.Ping buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Ping buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.pro.duplex.test.PingPong.Ping returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.duplex.test.PingPong.Ping) {
          return mergeFrom((com.googlecode.protobuf.pro.duplex.test.PingPong.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.duplex.test.PingPong.Ping other) {
        if (other == com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance()) return this;
        if (other.hasProcessingTime()) {
          setProcessingTime(other.getProcessingTime());
        }
        if (other.hasPongDataLength()) {
          setPongDataLength(other.getPongDataLength());
        }
        if (other.hasPingData()) {
          setPingData(other.getPingData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setProcessingTime(input.readInt32());
              break;
            }
            case 16: {
              setPongDataLength(input.readInt32());
              break;
            }
            case 26: {
              setPingData(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required int32 processingTime = 1;
      public boolean hasProcessingTime() {
        return result.hasProcessingTime();
      }
      public int getProcessingTime() {
        return result.getProcessingTime();
      }
      public Builder setProcessingTime(int value) {
        result.hasProcessingTime = true;
        result.processingTime_ = value;
        return this;
      }
      public Builder clearProcessingTime() {
        result.hasProcessingTime = false;
        result.processingTime_ = 0;
        return this;
      }
      
      // required int32 pongDataLength = 2;
      public boolean hasPongDataLength() {
        return result.hasPongDataLength();
      }
      public int getPongDataLength() {
        return result.getPongDataLength();
      }
      public Builder setPongDataLength(int value) {
        result.hasPongDataLength = true;
        result.pongDataLength_ = value;
        return this;
      }
      public Builder clearPongDataLength() {
        result.hasPongDataLength = false;
        result.pongDataLength_ = 0;
        return this;
      }
      
      // required bytes pingData = 3;
      public boolean hasPingData() {
        return result.hasPingData();
      }
      public com.google.protobuf.ByteString getPingData() {
        return result.getPingData();
      }
      public Builder setPingData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPingData = true;
        result.pingData_ = value;
        return this;
      }
      public Builder clearPingData() {
        result.hasPingData = false;
        result.pingData_ = getDefaultInstance().getPingData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Ping)
    }
    
    static {
      defaultInstance = new Ping(true);
      com.googlecode.protobuf.pro.duplex.test.PingPong.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Ping)
  }
  
  public static final class Pong extends
      com.google.protobuf.GeneratedMessage {
    // Use Pong.newBuilder() to construct.
    private Pong() {
      initFields();
    }
    private Pong(boolean noInit) {}
    
    private static final Pong defaultInstance;
    public static Pong getDefaultInstance() {
      return defaultInstance;
    }
    
    public Pong getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.duplex.test.PingPong.internal_static_Pong_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.duplex.test.PingPong.internal_static_Pong_fieldAccessorTable;
    }
    
    // required bytes pongData = 1;
    public static final int PONGDATA_FIELD_NUMBER = 1;
    private boolean hasPongData;
    private com.google.protobuf.ByteString pongData_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPongData() { return hasPongData; }
    public com.google.protobuf.ByteString getPongData() { return pongData_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasPongData) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPongData()) {
        output.writeBytes(1, getPongData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPongData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPongData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.duplex.test.PingPong.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.duplex.test.PingPong.Pong prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.duplex.test.PingPong.Pong result;
      
      // Construct using com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.duplex.test.PingPong.Pong();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.duplex.test.PingPong.Pong internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.duplex.test.PingPong.Pong();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.duplex.test.PingPong.Pong buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.pro.duplex.test.PingPong.Pong returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.duplex.test.PingPong.Pong) {
          return mergeFrom((com.googlecode.protobuf.pro.duplex.test.PingPong.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.duplex.test.PingPong.Pong other) {
        if (other == com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance()) return this;
        if (other.hasPongData()) {
          setPongData(other.getPongData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPongData(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes pongData = 1;
      public boolean hasPongData() {
        return result.hasPongData();
      }
      public com.google.protobuf.ByteString getPongData() {
        return result.getPongData();
      }
      public Builder setPongData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPongData = true;
        result.pongData_ = value;
        return this;
      }
      public Builder clearPongData() {
        result.hasPongData = false;
        result.pongData_ = getDefaultInstance().getPongData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Pong)
    }
    
    static {
      defaultInstance = new Pong(true);
      com.googlecode.protobuf.pro.duplex.test.PingPong.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Pong)
  }
  
  public static abstract class PingPongService
      implements com.google.protobuf.Service {
    protected PingPongService() {}
    
    public interface Interface {
      public abstract void ping(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done);
      
      public abstract void fail(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PingPongService() {
        @Override
        public  void ping(
            com.google.protobuf.RpcController controller,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
            com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done) {
          impl.ping(controller, request, done);
        }
        
        @Override
        public  void fail(
            com.google.protobuf.RpcController controller,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
            com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done) {
          impl.fail(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.ping(controller, (com.googlecode.protobuf.pro.duplex.test.PingPong.Ping)request);
            case 1:
              return impl.fail(controller, (com.googlecode.protobuf.pro.duplex.test.PingPong.Ping)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance();
            case 1:
              return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance();
            case 1:
              return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void ping(
        com.google.protobuf.RpcController controller,
        com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
        com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done);
    
    public abstract void fail(
        com.google.protobuf.RpcController controller,
        com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
        com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.duplex.test.PingPong.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.ping(controller, (com.googlecode.protobuf.pro.duplex.test.PingPong.Ping)request,
            com.google.protobuf.RpcUtil.<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong>specializeCallback(
              done));
          return;
        case 1:
          this.fail(controller, (com.googlecode.protobuf.pro.duplex.test.PingPong.Ping)request,
            com.google.protobuf.RpcUtil.<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance();
        case 1:
          return com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance();
        case 1:
          return com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.googlecode.protobuf.pro.duplex.test.PingPong.PingPongService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void ping(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.class,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance()));
      }
      
      public  void fail(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.pro.duplex.test.PingPong.Pong> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.class,
            com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong ping(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request)
          throws com.google.protobuf.ServiceException;
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong fail(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong ping(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request)
          throws com.google.protobuf.ServiceException {
        return (com.googlecode.protobuf.pro.duplex.test.PingPong.Pong) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance());
      }
      
      
      public com.googlecode.protobuf.pro.duplex.test.PingPong.Pong fail(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Ping request)
          throws com.google.protobuf.ServiceException {
        return (com.googlecode.protobuf.pro.duplex.test.PingPong.Pong) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Ping_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Pong_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Pong_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pingpong.proto\"H\n\004Ping\022\026\n\016processingTi" +
      "me\030\001 \002(\005\022\026\n\016pongDataLength\030\002 \002(\005\022\020\n\010ping" +
      "Data\030\003 \002(\014\"\030\n\004Pong\022\020\n\010pongData\030\001 \002(\0142=\n\017" +
      "PingPongService\022\024\n\004ping\022\005.Ping\032\005.Pong\022\024\n" +
      "\004fail\022\005.Ping\032\005.PongB3\n\'com.googlecode.pr" +
      "otobuf.pro.duplex.testB\010PingPong"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Ping_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Ping_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Ping_descriptor,
              new java.lang.String[] { "ProcessingTime", "PongDataLength", "PingData", },
              com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.class,
              com.googlecode.protobuf.pro.duplex.test.PingPong.Ping.Builder.class);
          internal_static_Pong_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Pong_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Pong_descriptor,
              new java.lang.String[] { "PongData", },
              com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.class,
              com.googlecode.protobuf.pro.duplex.test.PingPong.Pong.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
