// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filexfer.proto

package com.googlecode.protobuf.pro.stream.example.filexfer;

public final class FileXfer {
  private FileXfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Post extends
      com.google.protobuf.GeneratedMessage {
    // Use Post.newBuilder() to construct.
    private Post() {
      initFields();
    }
    private Post(boolean noInit) {}
    
    private static final Post defaultInstance;
    public static Post getDefaultInstance() {
      return defaultInstance;
    }
    
    public Post getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internal_static_Post_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internal_static_Post_fieldAccessorTable;
    }
    
    // required string filename = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private boolean hasFilename;
    private java.lang.String filename_ = "";
    public boolean hasFilename() { return hasFilename; }
    public java.lang.String getFilename() { return filename_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFilename) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFilename()) {
        output.writeString(1, getFilename());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFilename()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFilename());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post result;
      
      // Construct using com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post other) {
        if (other == com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          setFilename(other.getFilename());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFilename(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string filename = 1;
      public boolean hasFilename() {
        return result.hasFilename();
      }
      public java.lang.String getFilename() {
        return result.getFilename();
      }
      public Builder setFilename(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFilename = true;
        result.filename_ = value;
        return this;
      }
      public Builder clearFilename() {
        result.hasFilename = false;
        result.filename_ = getDefaultInstance().getFilename();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Post)
    }
    
    static {
      defaultInstance = new Post(true);
      com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Post)
  }
  
  public static final class Get extends
      com.google.protobuf.GeneratedMessage {
    // Use Get.newBuilder() to construct.
    private Get() {
      initFields();
    }
    private Get(boolean noInit) {}
    
    private static final Get defaultInstance;
    public static Get getDefaultInstance() {
      return defaultInstance;
    }
    
    public Get getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internal_static_Get_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internal_static_Get_fieldAccessorTable;
    }
    
    // required string filename = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private boolean hasFilename;
    private java.lang.String filename_ = "";
    public boolean hasFilename() { return hasFilename; }
    public java.lang.String getFilename() { return filename_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFilename) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFilename()) {
        output.writeString(1, getFilename());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFilename()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFilename());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get result;
      
      // Construct using com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get other) {
        if (other == com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          setFilename(other.getFilename());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFilename(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string filename = 1;
      public boolean hasFilename() {
        return result.hasFilename();
      }
      public java.lang.String getFilename() {
        return result.getFilename();
      }
      public Builder setFilename(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFilename = true;
        result.filename_ = value;
        return this;
      }
      public Builder clearFilename() {
        result.hasFilename = false;
        result.filename_ = getDefaultInstance().getFilename();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Get)
    }
    
    static {
      defaultInstance = new Get(true);
      com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Get)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Post_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Post_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Get_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Get_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016filexfer.proto\"\030\n\004Post\022\020\n\010filename\030\001 \002" +
      "(\t\"\027\n\003Get\022\020\n\010filename\030\001 \002(\tB?\n3com.googl" +
      "ecode.protobuf.pro.stream.example.filexf" +
      "erB\010FileXfer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Post_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Post_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Post_descriptor,
              new java.lang.String[] { "Filename", },
              com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.class,
              com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Post.Builder.class);
          internal_static_Get_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Get_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Get_descriptor,
              new java.lang.String[] { "Filename", },
              com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.class,
              com.googlecode.protobuf.pro.stream.example.filexfer.FileXfer.Get.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
