// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf-stream-log.proto

package com.googlecode.protobuf.pro.stream.logging;

public final class StreamLogEntry {
  private StreamLogEntry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum TransferType
      implements com.google.protobuf.ProtocolMessageEnum {
    PUSH(0, 1),
    PULL(1, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static TransferType valueOf(int value) {
      switch (value) {
        case 1: return PUSH;
        case 2: return PULL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<TransferType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TransferType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransferType>() {
            public TransferType findValueByNumber(int number) {
              return TransferType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final TransferType[] VALUES = {
      PUSH, PULL, 
    };
    public static TransferType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private TransferType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:TransferType)
  }
  
  public static final class Parameter extends
      com.google.protobuf.GeneratedMessage {
    // Use Parameter.newBuilder() to construct.
    private Parameter() {
      initFields();
    }
    private Parameter(boolean noInit) {}
    
    private static final Parameter defaultInstance;
    public static Parameter getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parameter getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internal_static_Parameter_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internal_static_Parameter_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter result;
      
      // Construct using com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter other) {
        if (other == com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Parameter)
    }
    
    static {
      defaultInstance = new Parameter(true);
      com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Parameter)
  }
  
  public static final class StreamTransfer extends
      com.google.protobuf.GeneratedMessage {
    // Use StreamTransfer.newBuilder() to construct.
    private StreamTransfer() {
      initFields();
    }
    private StreamTransfer(boolean noInit) {}
    
    private static final StreamTransfer defaultInstance;
    public static StreamTransfer getDefaultInstance() {
      return defaultInstance;
    }
    
    public StreamTransfer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internal_static_StreamTransfer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internal_static_StreamTransfer_fieldAccessorTable;
    }
    
    // required .TransferType transferType = 1;
    public static final int TRANSFERTYPE_FIELD_NUMBER = 1;
    private boolean hasTransferType;
    private com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType transferType_;
    public boolean hasTransferType() { return hasTransferType; }
    public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType getTransferType() { return transferType_; }
    
    // required string requestType = 2;
    public static final int REQUESTTYPE_FIELD_NUMBER = 2;
    private boolean hasRequestType;
    private java.lang.String requestType_ = "";
    public boolean hasRequestType() { return hasRequestType; }
    public java.lang.String getRequestType() { return requestType_; }
    
    // required int32 duration = 3;
    public static final int DURATION_FIELD_NUMBER = 3;
    private boolean hasDuration;
    private int duration_ = 0;
    public boolean hasDuration() { return hasDuration; }
    public int getDuration() { return duration_; }
    
    // required string server = 4;
    public static final int SERVER_FIELD_NUMBER = 4;
    private boolean hasServer;
    private java.lang.String server_ = "";
    public boolean hasServer() { return hasServer; }
    public java.lang.String getServer() { return server_; }
    
    // required string client = 5;
    public static final int CLIENT_FIELD_NUMBER = 5;
    private boolean hasClient;
    private java.lang.String client_ = "";
    public boolean hasClient() { return hasClient; }
    public java.lang.String getClient() { return client_; }
    
    // required int32 corId = 6;
    public static final int CORID_FIELD_NUMBER = 6;
    private boolean hasCorId;
    private int corId_ = 0;
    public boolean hasCorId() { return hasCorId; }
    public int getCorId() { return corId_; }
    
    // optional string error = 7;
    public static final int ERROR_FIELD_NUMBER = 7;
    private boolean hasError;
    private java.lang.String error_ = "";
    public boolean hasError() { return hasError; }
    public java.lang.String getError() { return error_; }
    
    // required int64 startTS = 8;
    public static final int STARTTS_FIELD_NUMBER = 8;
    private boolean hasStartTS;
    private long startTS_ = 0L;
    public boolean hasStartTS() { return hasStartTS; }
    public long getStartTS() { return startTS_; }
    
    // optional int32 sizeBytes = 9;
    public static final int SIZEBYTES_FIELD_NUMBER = 9;
    private boolean hasSizeBytes;
    private int sizeBytes_ = 0;
    public boolean hasSizeBytes() { return hasSizeBytes; }
    public int getSizeBytes() { return sizeBytes_; }
    
    // repeated .Parameter parameter = 10;
    public static final int PARAMETER_FIELD_NUMBER = 10;
    private java.util.List<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter> parameter_ =
      java.util.Collections.emptyList();
    public java.util.List<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter> getParameterList() {
      return parameter_;
    }
    public int getParameterCount() { return parameter_.size(); }
    public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter getParameter(int index) {
      return parameter_.get(index);
    }
    
    private void initFields() {
      transferType_ = com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType.PUSH;
    }
    public final boolean isInitialized() {
      if (!hasTransferType) return false;
      if (!hasRequestType) return false;
      if (!hasDuration) return false;
      if (!hasServer) return false;
      if (!hasClient) return false;
      if (!hasCorId) return false;
      if (!hasStartTS) return false;
      for (com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter element : getParameterList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTransferType()) {
        output.writeEnum(1, getTransferType().getNumber());
      }
      if (hasRequestType()) {
        output.writeString(2, getRequestType());
      }
      if (hasDuration()) {
        output.writeInt32(3, getDuration());
      }
      if (hasServer()) {
        output.writeString(4, getServer());
      }
      if (hasClient()) {
        output.writeString(5, getClient());
      }
      if (hasCorId()) {
        output.writeInt32(6, getCorId());
      }
      if (hasError()) {
        output.writeString(7, getError());
      }
      if (hasStartTS()) {
        output.writeInt64(8, getStartTS());
      }
      if (hasSizeBytes()) {
        output.writeInt32(9, getSizeBytes());
      }
      for (com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter element : getParameterList()) {
        output.writeMessage(10, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTransferType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getTransferType().getNumber());
      }
      if (hasRequestType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRequestType());
      }
      if (hasDuration()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getDuration());
      }
      if (hasServer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getServer());
      }
      if (hasClient()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getClient());
      }
      if (hasCorId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getCorId());
      }
      if (hasError()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getError());
      }
      if (hasStartTS()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, getStartTS());
      }
      if (hasSizeBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, getSizeBytes());
      }
      for (com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter element : getParameterList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer result;
      
      // Construct using com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer();
        return builder;
      }
      
      protected com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.getDescriptor();
      }
      
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer getDefaultInstanceForType() {
        return com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.parameter_ != java.util.Collections.EMPTY_LIST) {
          result.parameter_ =
            java.util.Collections.unmodifiableList(result.parameter_);
        }
        com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer) {
          return mergeFrom((com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer other) {
        if (other == com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.getDefaultInstance()) return this;
        if (other.hasTransferType()) {
          setTransferType(other.getTransferType());
        }
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasServer()) {
          setServer(other.getServer());
        }
        if (other.hasClient()) {
          setClient(other.getClient());
        }
        if (other.hasCorId()) {
          setCorId(other.getCorId());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasStartTS()) {
          setStartTS(other.getStartTS());
        }
        if (other.hasSizeBytes()) {
          setSizeBytes(other.getSizeBytes());
        }
        if (!other.parameter_.isEmpty()) {
          if (result.parameter_.isEmpty()) {
            result.parameter_ = new java.util.ArrayList<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter>();
          }
          result.parameter_.addAll(other.parameter_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType value = com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setTransferType(value);
              }
              break;
            }
            case 18: {
              setRequestType(input.readString());
              break;
            }
            case 24: {
              setDuration(input.readInt32());
              break;
            }
            case 34: {
              setServer(input.readString());
              break;
            }
            case 42: {
              setClient(input.readString());
              break;
            }
            case 48: {
              setCorId(input.readInt32());
              break;
            }
            case 58: {
              setError(input.readString());
              break;
            }
            case 64: {
              setStartTS(input.readInt64());
              break;
            }
            case 72: {
              setSizeBytes(input.readInt32());
              break;
            }
            case 82: {
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.Builder subBuilder = com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addParameter(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .TransferType transferType = 1;
      public boolean hasTransferType() {
        return result.hasTransferType();
      }
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType getTransferType() {
        return result.getTransferType();
      }
      public Builder setTransferType(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTransferType = true;
        result.transferType_ = value;
        return this;
      }
      public Builder clearTransferType() {
        result.hasTransferType = false;
        result.transferType_ = com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.TransferType.PUSH;
        return this;
      }
      
      // required string requestType = 2;
      public boolean hasRequestType() {
        return result.hasRequestType();
      }
      public java.lang.String getRequestType() {
        return result.getRequestType();
      }
      public Builder setRequestType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequestType = true;
        result.requestType_ = value;
        return this;
      }
      public Builder clearRequestType() {
        result.hasRequestType = false;
        result.requestType_ = getDefaultInstance().getRequestType();
        return this;
      }
      
      // required int32 duration = 3;
      public boolean hasDuration() {
        return result.hasDuration();
      }
      public int getDuration() {
        return result.getDuration();
      }
      public Builder setDuration(int value) {
        result.hasDuration = true;
        result.duration_ = value;
        return this;
      }
      public Builder clearDuration() {
        result.hasDuration = false;
        result.duration_ = 0;
        return this;
      }
      
      // required string server = 4;
      public boolean hasServer() {
        return result.hasServer();
      }
      public java.lang.String getServer() {
        return result.getServer();
      }
      public Builder setServer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServer = true;
        result.server_ = value;
        return this;
      }
      public Builder clearServer() {
        result.hasServer = false;
        result.server_ = getDefaultInstance().getServer();
        return this;
      }
      
      // required string client = 5;
      public boolean hasClient() {
        return result.hasClient();
      }
      public java.lang.String getClient() {
        return result.getClient();
      }
      public Builder setClient(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasClient = true;
        result.client_ = value;
        return this;
      }
      public Builder clearClient() {
        result.hasClient = false;
        result.client_ = getDefaultInstance().getClient();
        return this;
      }
      
      // required int32 corId = 6;
      public boolean hasCorId() {
        return result.hasCorId();
      }
      public int getCorId() {
        return result.getCorId();
      }
      public Builder setCorId(int value) {
        result.hasCorId = true;
        result.corId_ = value;
        return this;
      }
      public Builder clearCorId() {
        result.hasCorId = false;
        result.corId_ = 0;
        return this;
      }
      
      // optional string error = 7;
      public boolean hasError() {
        return result.hasError();
      }
      public java.lang.String getError() {
        return result.getError();
      }
      public Builder setError(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasError = true;
        result.error_ = value;
        return this;
      }
      public Builder clearError() {
        result.hasError = false;
        result.error_ = getDefaultInstance().getError();
        return this;
      }
      
      // required int64 startTS = 8;
      public boolean hasStartTS() {
        return result.hasStartTS();
      }
      public long getStartTS() {
        return result.getStartTS();
      }
      public Builder setStartTS(long value) {
        result.hasStartTS = true;
        result.startTS_ = value;
        return this;
      }
      public Builder clearStartTS() {
        result.hasStartTS = false;
        result.startTS_ = 0L;
        return this;
      }
      
      // optional int32 sizeBytes = 9;
      public boolean hasSizeBytes() {
        return result.hasSizeBytes();
      }
      public int getSizeBytes() {
        return result.getSizeBytes();
      }
      public Builder setSizeBytes(int value) {
        result.hasSizeBytes = true;
        result.sizeBytes_ = value;
        return this;
      }
      public Builder clearSizeBytes() {
        result.hasSizeBytes = false;
        result.sizeBytes_ = 0;
        return this;
      }
      
      // repeated .Parameter parameter = 10;
      public java.util.List<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter> getParameterList() {
        return java.util.Collections.unmodifiableList(result.parameter_);
      }
      public int getParameterCount() {
        return result.getParameterCount();
      }
      public com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter getParameter(int index) {
        return result.getParameter(index);
      }
      public Builder setParameter(int index, com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.parameter_.set(index, value);
        return this;
      }
      public Builder setParameter(int index, com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.Builder builderForValue) {
        result.parameter_.set(index, builderForValue.build());
        return this;
      }
      public Builder addParameter(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.parameter_.isEmpty()) {
          result.parameter_ = new java.util.ArrayList<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter>();
        }
        result.parameter_.add(value);
        return this;
      }
      public Builder addParameter(com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.Builder builderForValue) {
        if (result.parameter_.isEmpty()) {
          result.parameter_ = new java.util.ArrayList<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter>();
        }
        result.parameter_.add(builderForValue.build());
        return this;
      }
      public Builder addAllParameter(
          java.lang.Iterable<? extends com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter> values) {
        if (result.parameter_.isEmpty()) {
          result.parameter_ = new java.util.ArrayList<com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter>();
        }
        super.addAll(values, result.parameter_);
        return this;
      }
      public Builder clearParameter() {
        result.parameter_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:StreamTransfer)
    }
    
    static {
      defaultInstance = new StreamTransfer(true);
      com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:StreamTransfer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Parameter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Parameter_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamTransfer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StreamTransfer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobuf-stream-log.proto\"(\n\tParameter" +
      "\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\335\001\n\016Stream" +
      "Transfer\022#\n\014transferType\030\001 \002(\0162\r.Transfe" +
      "rType\022\023\n\013requestType\030\002 \002(\t\022\020\n\010duration\030\003" +
      " \002(\005\022\016\n\006server\030\004 \002(\t\022\016\n\006client\030\005 \002(\t\022\r\n\005" +
      "corId\030\006 \002(\005\022\r\n\005error\030\007 \001(\t\022\017\n\007startTS\030\010 " +
      "\002(\003\022\021\n\tsizeBytes\030\t \001(\005\022\035\n\tparameter\030\n \003(" +
      "\0132\n.Parameter*\"\n\014TransferType\022\010\n\004PUSH\020\001\022" +
      "\010\n\004PULL\020\002B>\n*com.googlecode.protobuf.pro" +
      ".stream.loggingB\016StreamLogEntryH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Parameter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Parameter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Parameter_descriptor,
              new java.lang.String[] { "Name", "Value", },
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.class,
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.Parameter.Builder.class);
          internal_static_StreamTransfer_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_StreamTransfer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StreamTransfer_descriptor,
              new java.lang.String[] { "TransferType", "RequestType", "Duration", "Server", "Client", "CorId", "Error", "StartTS", "SizeBytes", "Parameter", },
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.class,
              com.googlecode.protobuf.pro.stream.logging.StreamLogEntry.StreamTransfer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
